spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/smart_home
    username: smart_home
    password: smart_home

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        default_schema: payment

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/