spring:
  application:
    name: aggregator

kafka:
  bootstrap-servers: localhost:9092

  consumer:
    group-id: aggregator
    auto-offset-reset: earliest
    enable-auto-commit: false

  topics:
    sensors: telemetry.sensors.v1
    snapshots: telemetry.snapshots.v1